# Render Blueprint Spec
# Docs: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: proyecto-progra
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
    autoDeploy: true
